"""Clicky-citation reasoning service.

When the operator clicks a citation chip in the Brief, we show:
  1. The source's logo (resolved on the UI from `source`)
  2. A deep-link to the actual record (resolved by citation_links)
  3. A short, well-written explanation of *why* this particular source
     record is relevant to the case's decision

(3) is generated by Gemini Flash 3.1 Lite using the case context + the
finding text that cites this record. We cache in `citation_reasonings`
so a chip clicked twice doesn't pay the LLM cost twice.

System prompt is tight: 2-3 plain-English sentences, no jargon, written
for a Director of Revenue Accounting. The prettifier already uses this
voice - we share the editorial direction.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from typing import Any
from uuid import UUID

import httpx

from manthan_api.db import get_conn

logger = logging.getLogger("manthan_api.citation_reasoning")

MODEL = os.environ.get("MANTHAN_CITATION_MODEL", "google/gemini-3.1-flash-lite")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"


SYSTEM_PROMPT = """You explain why ONE source record matters to a billing-dispute investigation. The reader is a Director of Revenue Accounting. They know about customers, charges, refunds, contracts, support tickets, accounts. They don't care about schemas, tables, columns, SQL, APIs, or any engineering jargon.

Write 2-3 short sentences (max ~50 words total). Plain English. No quotes. No emoji. No markdown. No bullet points. No trailing meta-commentary. Just the explanation.

Avoid the words: schema, table, column, query, SQL, API, endpoint, JSON, payload, row, record (use "entry" or just name the thing - "the charge", "the ticket", "the contract"), field (say "the email", "the date", etc).

Lead with what this entry IS in their world ("This is the original charge…", "This is the support ticket where…"), then say what it tells us about THE CASE ("It shows the customer agreed to the renewal in writing on May 3."). Close with what it means for the decision when relevant ("Strong evidence for fighting the chargeback.")."""


class CitationReasoningResult:
    __slots__ = ("source", "table", "ref", "field", "reasoning", "generated_at", "model", "cached")

    def __init__(
        self,
        source: str,
        table: str,
        ref: str,
        field: str | None,
        reasoning: str,
        generated_at: datetime,
        model: str | None,
        cached: bool,
    ) -> None:
        self.source = source
        self.table = table
        self.ref = ref
        self.field = field
        self.reasoning = reasoning
        self.generated_at = generated_at
        self.model = model
        self.cached = cached


async def get_or_generate_reasoning(
    *,
    org_id: UUID,
    case_id: UUID,
    source: str,
    table: str,
    ref: str,
    field: str | None,
) -> CitationReasoningResult:
    """Return cached reasoning if present, otherwise call LLM and persist."""
    field_key = field or ""

    # 1. Cache hit fast path.
    async with get_conn() as conn:
        row = await conn.fetchrow(
            """
            SELECT reasoning, model, generated_at
            FROM citation_reasonings
            WHERE org_id=$1 AND case_id=$2
              AND source=$3 AND table_name=$4 AND ref=$5 AND field=$6
            """,
            org_id, case_id, source, table, ref, field_key,
        )
    if row is not None:
        return CitationReasoningResult(
            source=source,
            table=table,
            ref=ref,
            field=field,
            reasoning=row["reasoning"],
            generated_at=row["generated_at"],
            model=row["model"],
            cached=True,
        )

    # 2. Cache miss - gather context, call LLM.
    context = await _build_context(org_id, case_id, source, table, ref, field_key)
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        # No key wired - synthesise a deterministic fallback so the UI
        # doesn't break in local dev. We don't cache the fallback.
        return _fallback(source, table, ref, field, context, model=None)

    user_msg = _build_prompt(context, source, table, ref, field_key)
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(20.0)) as http:
            r = await http.post(
                OPENROUTER_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                    "HTTP-Referer": "https://app.manthan.quest",
                    "X-Title": "Manthan citation reasoning",
                },
                json={
                    "model": MODEL,
                    "max_tokens": 200,
                    "temperature": 0.3,
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_msg},
                    ],
                },
            )
            r.raise_for_status()
            body: Any = r.json()
        reasoning = (
            ((body.get("choices") or [{}])[0].get("message") or {}).get("content")
            or ""
        ).strip()
    except Exception as e:  # noqa: BLE001
        logger.warning("citation reasoning LLM failed: %s", e)
        return _fallback(source, table, ref, field, context, model=None)

    if not reasoning:
        return _fallback(source, table, ref, field, context, model=None)

    reasoning = _normalize(reasoning)

    # 3. Persist. Upsert on the unique key in case of concurrent generation.
    async with get_conn() as conn:
        saved = await conn.fetchrow(
            """
            INSERT INTO citation_reasonings
                (org_id, case_id, source, table_name, ref, field, reasoning, model)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            ON CONFLICT (org_id, case_id, source, table_name, ref, field)
            DO UPDATE SET reasoning = EXCLUDED.reasoning,
                          model = EXCLUDED.model,
                          generated_at = now()
            RETURNING generated_at
            """,
            org_id, case_id, source, table, ref, field_key, reasoning, MODEL,
        )

    return CitationReasoningResult(
        source=source,
        table=table,
        ref=ref,
        field=field,
        reasoning=reasoning,
        generated_at=saved["generated_at"],
        model=MODEL,
        cached=False,
    )


async def list_reasonings_for_case(org_id: UUID, case_id: UUID) -> list[dict]:
    """Return every cached reasoning for a case (UI pre-warm)."""
    async with get_conn() as conn:
        rows = await conn.fetch(
            """
            SELECT source, table_name AS table, ref, field, reasoning,
                   model, generated_at
            FROM citation_reasonings
            WHERE org_id=$1 AND case_id=$2
            """,
            org_id, case_id,
        )
    return [
        {
            "source": r["source"],
            "table": r["table"],
            "ref": r["ref"],
            "field": r["field"] or None,
            "reasoning": r["reasoning"],
            "model": r["model"],
            "generated_at": r["generated_at"].isoformat(),
        }
        for r in rows
    ]


# ──────────────────────────────────────────────────────────────────────
# Context + prompt assembly
# ──────────────────────────────────────────────────────────────────────


async def _build_context(
    org_id: UUID,
    case_id: UUID,
    source: str,
    table: str,
    ref: str,
    field: str,
) -> dict:
    """Gather case + finding context for the LLM prompt."""
    async with get_conn() as conn:
        case_row = await conn.fetchrow(
            """
            SELECT short_id, status, case_type, customer_ref, amount_minor,
                   currency, decision_action, decision_amount_minor,
                   decision_confidence, thread_id
            FROM cases
            WHERE org_id=$1 AND id=$2
            """,
            org_id, case_id,
        )
        if case_row is None:
            return {"finding_texts": [], "tldr": None}

        # The brief TLDR (if any) - drops the postmortem summary in.
        brief_row = await conn.fetchrow(
            """
            SELECT data FROM events
            WHERE org_id=$1 AND thread_id=$2 AND type='brief_drafted'
            ORDER BY seq DESC LIMIT 1
            """,
            org_id, case_row["thread_id"],
        )
        tldr = None
        if brief_row:
            data = brief_row["data"]
            if isinstance(data, str):
                data = json.loads(data)
            tldr = (data or {}).get("tldr")

        # Findings that cite this exact (source, table, ref). We
        # check each finding's citations array for a match.
        finding_rows = await conn.fetch(
            """
            SELECT seq, text, citations
            FROM findings
            WHERE org_id=$1 AND case_id=$2
            ORDER BY seq ASC
            """,
            org_id, case_id,
        )

    finding_texts: list[str] = []
    for f in finding_rows:
        cites = f["citations"]
        if isinstance(cites, str):
            try:
                cites = json.loads(cites)
            except Exception:
                cites = []
        if not isinstance(cites, list):
            continue
        for c in cites:
            if not isinstance(c, dict):
                continue
            if (
                c.get("source") == source
                and c.get("table") == table
                and c.get("ref") == ref
            ):
                finding_texts.append(f["text"])
                break

    return {
        "short_id": case_row["short_id"],
        "case_type": case_row["case_type"],
        "customer_ref": case_row["customer_ref"],
        "amount_minor": case_row["amount_minor"],
        "currency": case_row["currency"],
        "decision_action": case_row["decision_action"],
        "decision_amount_minor": case_row["decision_amount_minor"],
        "decision_confidence": (
            float(case_row["decision_confidence"])
            if case_row["decision_confidence"] is not None
            else None
        ),
        "tldr": tldr,
        "finding_texts": finding_texts,
    }


def _build_prompt(
    ctx: dict,
    source: str,
    table: str,
    ref: str,
    field: str,
) -> str:
    amt = ctx.get("amount_minor")
    amt_str = (
        f"${(amt or 0) / 100:,.0f} {(ctx.get('currency') or 'usd').upper()}"
        if amt else "-"
    )
    decision = ctx.get("decision_action") or "(pending)"
    conf = ctx.get("decision_confidence")
    conf_str = f"{int(conf * 100)}%" if conf is not None else "-"
    findings = ctx.get("finding_texts") or []
    finding_block = (
        "\n".join(f"  - {t}" for t in findings[:6])
        if findings
        else "  (no finding explicitly cites this entry)"
    )

    return (
        f"CASE: {ctx.get('customer_ref') or 'Unknown customer'} · "
        f"{ctx.get('case_type') or 'case'} · {amt_str}\n"
        f"DECISION: {decision} (confidence {conf_str})\n"
        f"BRIEF TLDR: {ctx.get('tldr') or '(none yet)'}\n\n"
        f"CITATION:\n"
        f"  Source: {source}\n"
        f"  Entry: {table} / {ref}\n"
        f"  Specific aspect: {field or '(the entry as a whole)'}\n\n"
        f"FINDINGS that cite this entry:\n"
        f"{finding_block}\n\n"
        f"Explain in 2-3 plain-English sentences why this entry matters for "
        f"the decision above."
    )


def _normalize(s: str) -> str:
    """Strip wrapping quotes, collapse whitespace, drop boilerplate prefix."""
    s = s.strip().strip('"').strip("'").strip()
    s = " ".join(s.split())
    for prefix in ("Reasoning:", "Explanation:", "Answer:", "Citation:"):
        if s.lower().startswith(prefix.lower()):
            s = s[len(prefix):].strip()
    return s[:1200]


def _fallback(
    source: str,
    table: str,
    ref: str,
    field: str | None,
    ctx: dict,
    *,
    model: str | None,
) -> CitationReasoningResult:
    """Deterministic fallback when the LLM call fails / no API key."""
    findings = ctx.get("finding_texts") or []
    if findings:
        snippet = findings[0]
        # Keep it short
        if len(snippet) > 240:
            snippet = snippet[:237] + "…"
        reasoning = (
            f"This {source} entry ({table} / {ref}) is cited in the "
            f"investigation: {snippet}"
        )
    else:
        reasoning = (
            f"This {source} entry was referenced by the agent while "
            f"investigating the case. Open the source to see the full record."
        )
    return CitationReasoningResult(
        source=source,
        table=table,
        ref=ref,
        field=field,
        reasoning=reasoning,
        generated_at=datetime.utcnow(),
        model=model,
        cached=False,
    )
